# Generated by Django 4.2.29 on 2026-03-31 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("buybackprogram", "0001_initial_sde"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveEntity",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "category",
                    models.TextField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("character", "Character"),
                            ("constellation", "Constellation"),
                            ("corporation", "Corporation"),
                            ("inventory_type", "Inventory Type"),
                            ("region", "Region"),
                            ("solar_system", "Solar System"),
                            ("station", "Station"),
                            ("faction", "Faction"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="contractitem",
            name="eve_type",
            field=models.ForeignKey(
                help_text="Item type information",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyback_contract_item_eve_type",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="itemprices",
            name="eve_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyback_item_prices_eve_type",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="programitem",
            name="item_type",
            field=models.ForeignKey(
                help_text="Select item for special tax",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyback_program_item_item_type",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="trackingitem",
            name="eve_type",
            field=models.ForeignKey(
                help_text="Item type information",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyback_tracking_item_eve_type",
                to="eve_sde.itemtype",
            ),
        ),
    ]
