# Generated by Django 4.2.29 on 2026-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("buybackprogram", "0001_initial_sde"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveEntity",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                (
                    "category",
                    models.TextField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("character", "Character"),
                            ("constellation", "Constellation"),
                            ("corporation", "Corporation"),
                            ("inventory_type", "Inventory Type"),
                            ("region", "Region"),
                            ("solar_system", "Solar System"),
                            ("station", "Station"),
                            ("faction", "Faction"),
                        ]
                    ),
                ),
            ],
        ),
    ]
