# Generated by Django 4.2.11 on 2024-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybackprogram', '0014_program_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractnotification',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
