# Generated by Django 4.2.11 on 2024-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybackprogram', '0015_faq_contractnotification_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
