# Generated by Django 4.2.11 on 2024-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buybackprogram', '0015_contractnotification_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractnotification',
            old_name='title',
            new_name='header',
        ),
    ]
