# Generated by Django 4.2.11 on 2024-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybackprogram', '0016_contract_additional_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='tracking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
