# Generated by Django 4.2.29 on 2026-03-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0018_blueprintactivity_blueprintactivityproduct_and_more"),
        ("buybackprogram", "0017_alter_contract_price_alter_contract_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractitem",
            name="eve_type",
            field=models.ForeignKey(
                help_text="Item type information",
                on_delete=django.db.models.deletion.CASCADE,
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="itemprices",
            name="eve_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="eve_sde.itemtype"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="eve_solar_system",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="System where the buyback structure is located",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="+",
                to="eve_sde.solarsystem",
                verbose_name="Solar system",
            ),
        ),
        migrations.AlterField(
            model_name="programitem",
            name="item_type",
            field=models.ForeignKey(
                help_text="Select item for special tax",
                on_delete=django.db.models.deletion.CASCADE,
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="trackingitem",
            name="eve_type",
            field=models.ForeignKey(
                help_text="Item type information",
                on_delete=django.db.models.deletion.CASCADE,
                to="eve_sde.itemtype",
            ),
        ),
    ]
